=== voltron42/nukular-riposte/eco.dtd
<!ELEMENT ecosystem (styles?, dependencies?, body?)>
<!ATTLIST ecosystem root-namespace CDATA #IMPLIED>
<!ELEMENT styles ((link|style)*)>
<!ATTLIST styles
common-style-path CDATA #IMPLIED
>
<!ELEMENT link EMPTY>
<!ATTLIST link
href CDATA #IMPLIED
>
<!ELEMENT style ANY>
<!ATTLIST style
type CDATA #IMPLIED
>
<!ELEMENT dependencies (script*)>
<!ATTLIST dependencies
common-dependencies-path CDATA #IMPLIED
>
<!ELEMENT script ANY>
<!ATTLIST script
src CDATA #IMPLIED
type CDATA #IMPLIED
crossorigin (anonymous|use-credentials) "anonymous"
>
<!ELEMENT body (hidden-header?,(header-root|static-header)?,root,(footer-root|static-footer)?,hidden-footer?)>
<!ATTLIST body
class CDATA #IMPLIED
style CDATA #IMPLIED
>
<!ELEMENT hidden-header ANY>
<!ELEMENT static-header ANY>
<!ELEMENT header-root (component-property*)>
<!ATTLIST header-root
id CDATA #REQUIRED
class CDATA #IMPLIED
style CDATA #IMPLIED
component-namespace CDATA #REQUIRED
component-alias CDATA #REQUIRED
>
<!ELEMENT root EMPTY>
<!ATTLIST root
id CDATA #REQUIRED
class CDATA #IMPLIED
style CDATA #IMPLIED
>
<!ELEMENT footer-root (component-property*)>
<!ATTLIST footer-root
id CDATA #REQUIRED
class CDATA #IMPLIED
style CDATA #IMPLIED
component-namespace CDATA #REQUIRED
component-alias CDATA #REQUIRED
>
<!ELEMENT component-property EMPTY>
<!ATTLIST component-property
name CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ELEMENT static-footer ANY>
<!ELEMENT hidden-footer ANY>

=== voltron42/nukular-riposte/demo-eco.xml
<?xml version="1.0"?>
<!DOCTYPE ecosystem SYSTEM "eco.dtd">
<ecosystem root-namespace="">
    <styles common-style-path="">
        <link href=""/>
        <style type="text/css">
        </style>
    </styles>
    <dependencies common-dependencies-path="">
        <script type="text/javascript" src=""></script>
        <script type="text/javascript">
        </script>
    </dependencies>
    <body>
        <hidden-header></hidden-header>
        <header-root id="" component-namespace="" component-alias="">
            <component-property name="" value="" />
        </header-root>
        <root id=""/>
        <footer-root id="" component-namespace="" component-alias="">
            <component-property name="" value="" />
        </footer-root>
        <hidden-footer></hidden-footer>
    </body>
</ecosystem>
